# Generated by Django 3.0.2 on 2020-01-19 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_myfavoritemovies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myfavoritemovies',
            old_name='idMovie',
            new_name='movie',
        ),
    ]
